### ISSUE TITLE
[Epic] YAML GA

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-yaml#269]
## Overview

This issue is an "epic" tracking the list of issues to be completed before the YAML language provider becomes generally available. Currently, this list is being built and should not be considered anywhere close to exhaustive. It will hold the issues that we know we need to address, but more issues will be added over time based on user feedback and other discoveries.

### M75

- [x] https://github.com/pulumi/pulumi-yaml/issues/271
- [x] https://github.com/pulumi/pulumi-yaml/issues/222
- [x] https://github.com/pulumi/pulumi-yaml/issues/242
- Reach feature completion for `pulumi convert`
  - [x] https://github.com/pulumi/pulumi-yaml/issues/25
  - [x] https://github.com/pulumi/pulumi/issues/10033
  - [x] https://github.com/pulumi/pulumi-yaml/issues/263
  - [x] https://github.com/pulumi/pulumi-yaml/issues/253
  - [x] https://github.com/pulumi/pulumi-yaml/issues/150
  - [x] https://github.com/pulumi/pulumi/issues/10098
  - [x] https://github.com/pulumi/pulumi-yaml/issues/254
  - [x] https://github.com/pulumi/pulumi/issues/8076
  - [x] https://github.com/pulumi/pulumi/issues/6510
  - [x] https://github.com/pulumi/pulumi/issues/10196
  - [x] https://github.com/pulumi/pulumi/issues/6505
- [x] https://github.com/pulumi/pulumi-yaml/issues/198
- [x] https://github.com/pulumi/pulumi-yaml/issues/155

### M76

- [x] https://github.com/pulumi/pulumi-yaml/issues/246
- [x] https://github.com/pulumi/pulumi-yaml/issues/246
- [x] https://github.com/pulumi/pulumi-yaml/issues/288
- [x] https://github.com/pulumi/pulumi-yaml/issues/293
- [x] https://github.com/pulumi/pulumi-yaml/issues/122

### M77

- [x] https://github.com/pulumi/pulumi-yaml/issues/283
- [x] https://github.com/pulumi/pulumi/issues/10260
- [x] https://github.com/pulumi/pulumi-yaml/issues/244
- [x] https://github.com/pulumi/pulumi-yaml/issues/303
- [x] https://github.com/pulumi/pulumi-yaml/issues/288
- [x] https://github.com/pulumi/pulumi-yaml/issues/293
- [x] https://github.com/pulumi/pulumi-yaml/issues/122

### M78

- [x] https://github.com/pulumi/pulumi-yaml/issues/302
- [x] https://github.com/pulumi/pulumi/issues/10358
- [x] https://github.com/pulumi/pulumi/issues/10195
- [x] https://github.com/pulumi/pulumi/issues/10466
- [x] https://github.com/pulumi/pulumi-yaml/issues/330

### M79
- [x] https://github.com/pulumi/pulumi-yaml/issues/355
- [x] https://github.com/pulumi/pulumi-yaml/issues/251
- [x] https://github.com/pulumi/pulumi-yaml/issues/359
- [x] https://github.com/pulumi/pulumi-yaml/issues/377

### M80
- [x] #369

### Work items ⚙️

- [x] Align `configuration` key and plan with hierarchical config:
  - [ ] https://github.com/pulumi/pulumi/issues/2307
- [ ] Scope and implement any additional `Fn::`. See the following threads (this is not a commitment to implement) for relevant discussion:
  - [x] https://github.com/pulumi/pulumi-str/issues/6
  - [x] https://github.com/pulumi/pulumi-yaml/issues/225

**Comment by lukehoban** [comment]
WE shipped YAML GA! 🎉 

https://www.pulumi.com/blog/pulumi-yaml-ga/
