### ISSUE TITLE
[Epic] YAML: public preview

### ISSUE THREAD

**Issue by infin8x** [pulumi/pulumi-yaml#64]
Pulumi aims to have the widest collection of supported programming languages, but today is missing the most common option in the IaC space - a simple declarative language.  We have seen this as a common cause of adoption/sales losses, and a significant limiter on our reach in the modern IaC market.  We will introduce a preview of support for a new YAML/JSON language provider, enabling a very simple declarative option for authoring Pulumi programs.

### Design and specification 📔

- [x] [PR/FAQ](https://docs.google.com/document/d/1XMz6CFSg2spYSw4AAi9CEyAgt7nT_cJyQbPU-B-NrCo/edit#)
- [x] [Spec](https://github.com/pulumi/pulumi-yaml#spec)
- [x] [Narrative](https://docs.google.com/document/d/17g55WNdwCi24XWUhMuYCRiqZ4r-RSzRrRzet4XXal-0/edit)
- [ ] Identify measures of success and note them in engineering :point_down:
- [ ] Identify preview customers and note them in launch readiness :point_down:

### Engineering ⚙️

Costed plan: https://docs.google.com/spreadsheets/d/1mO6mEY4f4Mm4_ol1zsZeRvQ9skXH-jEbXS4-HkZLPsA/edit#gid=0

M68:
- [x] pulumi/pulumi-yaml#31
- [x] pulumi/pulumi-yaml#30
- [x] pulumi/pulumi-yaml#20

M69:
- [x] pulumi/pulumi-yaml#8
- [x] pulumi/pulumi-yaml#9
- [x] pulumi/pulumi-yaml#10
- [x] pulumi/pulumi-yaml#14
- [x] pulumi/pulumi-yaml#23

M70:
- [x] pulumi/pulumi-yaml#6
- [x] pulumi/pulumi-yaml#7
- [x] pulumi/pulumi-yaml#21
- [x] pulumi/pulumi-yaml#41
- [x] pulumi/pulumi-yaml#12

M71 pre-launch:

- [x] https://github.com/pulumi/pulumi-yaml/issues/143
- [x] #147 
- [x] #163
- [x] pulumi/pulumi-yaml#51
- [x] pulumi/pulumi-yaml#22
- [ ] #117
  - [x] https://github.com/pulumi/pulumi/pull/9290
- [ ] #79
- [x] #169
- [x] #174
- [x] #175

M71 launch day:
- [ ] Distribute with pulumi/pulumi: pulumi/pulumi-yaml#11
- [x] Add dependency on pulumi-yaml from pulumi/pulumi for `pulumi convert` #118 

Post-launch:
- [ ] pulumi/pulumi-yaml#24
- [ ] pulumi/pulumi-yaml#25
- [ ] pulumi/pulumi-yaml#26
- [ ] https://github.com/pulumi/pulumi/issues/9388

### Launch readiness 🎁

Docs & Pulumi.com updates:
- pulumi.com/registry: 
  - [x] pulumi/pulumi-yaml#15
  - [x] pulumi/registry#603
  - [x] https://github.com/pulumi/pulumi-yaml/issues/173
- pulumi.com/docs/get-started 
    - [x] pulumi/pulumi-yaml#16
    - [ ] https://github.com/pulumi/pulumi-yaml/issues/142
    - [x] Get examples for to content engineering for AWS, Azure, Google, Kubernetes
- [ ] pulumi.com/docs/guides*
- [x] pulumi.com/docs/reference/*
- [x] pulumi.com/docs/intro/concepts/* pulumi/pulumi-yaml#17
- [x] `pulumi new` support pulumi/pulumi-yaml#18
- [x] pulumi.com/docs/intro/languages/* pulumi/pulumi-yaml#19

## [Objective and Key Results](https://docs.google.com/document/d/1sjv6_hITtNy1oHGS6iBiDtg11vIo7ncsy5QkClxyISQ/edit#)

- **Objective:** Deliver a popular and innovative Cloud Engineering Platform.
  - **Key result:** YAML language SDK public preview
